site_name: Merox Dev
site_url: https://merox.dev
repo_url: https://github.com
repo_name: mer0x/merox.dev
theme:
  custom_dir: assets
  favicon: images/merox.png
  logo: images/meroxdev.png
  name: material
  features:
    - header.autohide
    - navigation.path
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.sections
    - navigation.footer
   # - toc.integrate
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
    - content.code.copy
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode


    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference


nav:
  - Home: index.md
  - Homelab:
    - Infrastructure: homelab/infrastructure.md
    - Connectivity: homelab/connectivity.md
    - Hypervisors: homelab/hypervisors.md
    - Virtual Machines: homelab/virtual-machines.md
    - Docker: homelab/docker.md
    - Kubernetes: homelab/kubernetes.md
    - Ansible: homelab/ansible.md
    - Protection: homelab/security.md
    - System Monitoring: homelab/monitoring.md
  - Fundamentals : 
    - Intro: fundamentals/intro.md
    - Networking: 
      - Configs: 
        - DNS: fundamentals/networking/configs/DNS.md
        - DHCP: fundamentals/networking/configs/DHCP.md
      - Cisco: 
        - Install:
          - ASA: fundamentals/networking/cisco/install/firewall.md
          - Router: fundamentals/networking/cisco/install/router.md
          - Switch: fundamentals/networking/cisco/install/switch.md
          - VPN:
            - IPsec over GRE: fundamentals/networking/cisco/install/ipsecgre.md

      - CCNA:
        - Cheatsheet: fundamentals/networking/ccna/cheatsheet.md
    - Operating Systems: 
      - Linux: 
         - Install:
           - Ubuntu cloud-init: fundamentals/operating-systems/linux/install/ubuntu-cloud-init.md
         - Config:
           - UFW: fundamentals/operating-systems/linux/config/ufw.md
           - Extend LVM: fundamentals/operating-systems/linux/config/extend-lvm-proxmox.md
         - T-shoot:
           - GRUB recovery: fundamentals/operating-systems/linux/tshoot/grub.md 
           - Root password recovery: fundamentals/operating-systems/linux/tshoot/root-password-recovery.md
           - Proxmox e1000 driver hang: fundamentals/operating-systems/linux/tshoot/proxmox-e1000.md
      - Windows: 
         - Install:
           - Windows Server 2019: fundamentals/operating-systems/windows/install/wserver2019.md
         - Config:
           - Active Directory: fundamentals/operating-systems/windows/config/active-directory.md
         - T-shoot:
           - DNS: fundamentals/operating-systems/windows/tshoot/dns.md
    - Database:
      - MySQL:
        - Basics: fundamentals/database/mysql/basics.md
      - InfluxDB:
        - Basics: fundamentals/database/influxdb/basics.md
    - Backup:
      - Clonezilla: fundamentals/backup/clonezilla.md

  - Operations : 
    - Intro: operations/intro.md
    - Virtualization: 
      - VMs: 
        - Proxmox: operations/virtualization/VMs/proxmox.md

    - Containerization: 
      - Kubernetes/K3S: operations/containerization/kubernetes.md
      - K3S:
        - Installation: operations/containerization/k3s/installation.md
        - Upgrade: operations/containerization/k3s/upgrade.md
        - Manifests:
          - Homepage: operations/containerization/k3s/manifests/dashboard.md
          - Loki: operations/containerization/k3s/manifests/loki.md
          - WikiJS: operations/containerization/k3s/manifests/wikijs.md
          - Netdata: operations/containerization/k3s/manifests/netdata.md
          - WordPress: operations/containerization/k3s/manifests/wordpress.md
          - ArgoCD: operations/containerization/k3s/manifests/argocd.md
          - Traefik: operations/containerization/k3s/manifests/traefik.md
          - Expose Service: operations/containerization/k3s/manifests/expose-service.md
          - Cert Manager: operations/containerization/k3s/manifests/cert-manager.md
          - Monitor Stack: operations/containerization/k3s/manifests/monitor-stack.md
          - Media Stack: operations/containerization/k3s/manifests/media-stack.md
          - NFS Share: operations/containerization/k3s/manifests/nfs-share.md
      - LXC:
        - Proxmox: operations/containerization/LXCs/proxmox.md
      - Docker:
        - Docker-Compose:
          - Monitoring Stack: operations/containerization/docker/docker-compose/monitoring-stack.md
          - Media Stack: operations/containerization/docker/docker-compose/media-stack.md
          - WordPress: operations/containerization/docker/docker-compose/wordpress.md
          - Uptime KUMA: operations/containerization/docker/docker-compose/uptime-kuma.md
          - InfluxDB: operations/containerization/docker/docker-compose/influxdb.md
          - Cloudflare: operations/containerization/docker/docker-compose/cloudflare.md
    - Cybersecurity:
      - Pentesting: 
        - Tools: operations/Cybersecurity/pentesting/tools.md
    - DevOps:
      - Ansible: 
        - Playbooks:
          - Linux upgrades: operations/DevOps/ansible/playbooks/linux-upgrade.md
          - Windows upgrades: operations/DevOps/ansible/playbooks/windows-upgrade.md
          - Proxmox VM: operations/DevOps/ansible/playbooks/proxmox-vm.md
    - Monitoring:
      - Grafana: 
        - Basics: operations/monitoring/grafana/basics.md
        - Prometheus w/ Alertmanager: operations/monitoring/grafana/prometheus-alertmanager.md
#      - Prometheus:
#        - Basics: operations/monitoring/prometheus/basics.md
#      - Alertmanager:
#        - Basics: operations/monitoring/alertmanager/basics.md
  - About: about.md
  - Blog:
      - Overview: blog/
      - Categories:
          - Server: blog/category/server
          - Installation: blog/category/installation
          - Networking: blog/category/networking
      - Archives:
          - 2024: blog/archive/2024




plugins:
  - social:
      cards: true
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: mer0x/merox.cloud
      branch: master
  - blog:
      archive: true
      categories: true
extra_css:
  - stylesheets/extra.css
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
      adsense:
        name: Google AdSense
        checked: true
  analytics:
    provider: google
    property: G-RXSCNFY5WZ
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >-
          Thanks for your feedback!
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! Help us improve this page by
          using our feedback form.

  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/robertmelcher97
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/merox.dev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/robert-melcher-92a1a9157
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/u/merox57/s/9OgwH5Q6Rq
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mer0x


  # Custom Homepage Elements
  home_cover_image: images/meroxdc.webp
  home_tagline: hello there
  home_description: |
   I’m an System Administrator with a background in Cybersecurity and a strong passion for Linux, Networking, and Security. Here, you'll find a range of documentation, blog posts, and tutorials based on my practical experience over the last 10 years.<br><br>

  # Gradient Color
  home_gradient_hsla:  hsla(0, 0%, 15%, 1)

  # Custom Homepage Button(s)
  home_button1_name: Get Started
  home_button1_url: homelab/infrastructure/
  home_button1_theme: md-button md-button--primary
  home_button1_icon: people
  home_button1_blurb: |
    This joker navigates to the shadow wizard armory located in "/Folder1/index.md"

  home_button2_name: Resources
  home_button2_url: /blog
  home_button2_theme: md-button
  home_button2_icon: gear
  home_button2_blurb: |
    This goober navigates to some important thingies located in "/Folder2/index.md"

  home_button3_name: About
  home_button3_url: Folder3/
  home_button3_theme: md-button
  home_button3_icon: image
  home_button3_blurb: |
    This psycho navigates to an interesting table of stuff located in "/Folder3/index.md"

  # Homepage Code Execution
  home_execute_js: |
    console.log("created by Robert Melcher");


markdown_extensions:
  - footnotes
  - md_in_html 
  - toc:
      permalink: false
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
       kwds:
         case: lower
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  Copyright &copy; 2024 Robert Melcher | 
  <a href="#__consent">Change cookie settings</a>
